---
#example: use of local variables within playbook
- name: Playbook for Mysql server
  hosts: dbservers
  vars:
   dbname: accounts
   dbuser: admin
   dbpass: admin123
  tasks:
    - debug:
        msg: "{{dbname, dbuser}}"
    
    - name: Install mysql-server package
      apt:
        name: ['mysql-server', 'python-mysqldb', 'git', 'wget', 'unzip']
        state: latest
        update_cache: yes

    - name:  start my sql server
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create new database with names 'accounts'
      mysql_db:
        name: '{{dbname}}'
        state: present

    - mysql_user:
        name: '{{dbuser}}'
        password: '{{dbpass}}'
        priv: '*.*:ALL'
        state: present
