---
- name: List the gather facts
  hosts: all
  tasks:
    - debug:
        msg: "{{ansible_os_family}}" 
    - debug:
        msg: "{{ansible_default_ipv4.macaddress}}" 
    - debug:
        msg: "OS is SuSE Based" 
      when: ansible_os_family == "Suse"
